=== Endrelish/PKCK/2/films.dtd
<?xml version='1.0' encoding='UTF-8'?>
        <!ENTITY % Ocena "(1|2|3|4|5)">
        <!ELEMENT BazaFilmów (Autorzy,Gatunki,Filmy)>

        <!ELEMENT Autorzy (Autor)*>

        <!ELEMENT Autor (Imię+,Nazwisko,Indeks)>

        <!ELEMENT Imię (#PCDATA)>

        <!ELEMENT Nazwisko (#PCDATA)>
        <!ELEMENT Indeks (#PCDATA)>

        <!ELEMENT Gatunki (Gatunek)*>

        <!ELEMENT Gatunek EMPTY>
        <!ATTLIST Gatunek
                Nazwa CDATA #REQUIRED
                Id ID #REQUIRED
                >

        <!ELEMENT Filmy (Film)*>

        <!ELEMENT Film (Tytuł,OryginalnyTytuł?,DataPremiery,Kraje,Reżyser, Cena)>
        <!ATTLIST Film
                IdGatunku IDREF #REQUIRED
                Ocena %Ocena; #REQUIRED
                >

        <!ELEMENT Tytuł (#PCDATA)>
        <!ELEMENT OryginalnyTytuł (#PCDATA)>

        <!ELEMENT DataPremiery (#PCDATA)>
        <!ELEMENT Kraje (Kraj+)>
        <!ELEMENT Kraj (#PCDATA)>


        <!ELEMENT Reżyser (#PCDATA)>
        <!ELEMENT Cena (#PCDATA)>

=== Endrelish/PKCK/1/films.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BazaFilmów SYSTEM "films.dtd" >
<?xml-stylesheet type="text/css" href="filmsStylesheet.css"?>
<BazaFilmów>
<Autorzy>
    <Autor>
        <Imię>Bartłomiej</Imię>
        <Nazwisko>Ciach</Nazwisko>
    </Autor>    
    <Autor>
        <Imię>Paweł</Imię>
        <Nazwisko>Purgat</Nazwisko>
    </Autor>
</Autorzy>


    <Gatunki>
        <Gatunek Nazwa="Dramat" Id="Dramat"/>
        <Gatunek Nazwa="Komedia" Id="Komedia"/>
        <Gatunek Nazwa="Sci-Fi" Id="Sci-Fi"/>           
    </Gatunki>
    
    
    
    <Filmy>
        <Film IdGatunku="Dramat" Ocena="5">
            <Tytuł>Zielona Mila</Tytuł>
            <DataPremiery>06-12-1999</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Frank Darabont</Reżyser>
        </Film>
        <Film IdGatunku="Dramat" Ocena="4">
            <Tytuł>Skazani na Shawshank</Tytuł>
            <DataPremiery>06-12-1994</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Frank Darabont</Reżyser>
        </Film>
        <Film IdGatunku="Dramat" Ocena="5">
            <Tytuł>Taksówkarz</Tytuł>
            <DataPremiery>06-12-1976</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Martin Scorsese</Reżyser>
        </Film>
        <Film IdGatunku="Dramat" Ocena="4">
            <Tytuł>Babel</Tytuł>
            <DataPremiery>06-12-2006</DataPremiery>
            <Kraj>Francja</Kraj>
            <Kraj>Meksyk</Kraj>
            <Kraj>USA</Kraj>
            <Reżyser>Alejandro Gonzalez Inarritu</Reżyser>
        </Film>
        <Film IdGatunku="Dramat" Ocena="5">
            <Tytuł>Życie za życie</Tytuł>
            <DataPremiery>06-12-2003</DataPremiery>
            <Kraj>Niemcy</Kraj>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>Alan Parker</Reżyser>
        </Film>
        <Film IdGatunku="Dramat" Ocena="4">
            <Tytuł>Wszyscy jesteśmy Chrystusami</Tytuł>
            <DataPremiery>06-12-2006</DataPremiery>
            <Kraj>Polska</Kraj>
            <Reżyser>Marek Koterski</Reżyser>
        </Film>
        <Film IdGatunku="Sci-Fi" Ocena="5">
            <Tytuł>Avatar</Tytuł>
            <DataPremiery>06-12-2009</DataPremiery>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>James Cameron</Reżyser>
        </Film>
        <Film IdGatunku="Sci-Fi" Ocena="4">
            <Tytuł>Terminator</Tytuł>
            <DataPremiery>06-12-1984</DataPremiery>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>James Cameron</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="5">
            <Tytuł>Bruce Wszechmogący</Tytuł>
            <DataPremiery>06-12-2003</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Tom Shadyac</Reżyser>
        </Film>
         <Film IdGatunku="Sci-Fi" Ocena="4">
            <Tytuł>Interstellar</Tytuł>
            <DataPremiery>06-12-2014</DataPremiery>
            <Kraj>Kanada</Kraj>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>Christopher Nolan</Reżyser>
        </Film>
        <Film IdGatunku="Sci-Fi" Ocena="5">
            <Tytuł>Iron Man</Tytuł>
            <DataPremiery>06-12-2008</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Jon Favreau</Reżyser>
        </Film>
        <Film IdGatunku="Sci-Fi" Ocena="5">
            <Tytuł>Avengers</Tytuł>
            <DataPremiery>06-12-2012</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Joss Whedon</Reżyser>
        </Film>
        <Film IdGatunku="Sci-Fi" Ocena="4">
            <Tytuł>Marsjanin</Tytuł>
            <DataPremiery>06-12-2015</DataPremiery>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>Ridley Scott</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="5">
            <Tytuł>Killer</Tytuł>
            <DataPremiery>06-12-1997</DataPremiery>
            <Kraj>Polska</Kraj>
            <Reżyser>Janusz Machulski</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="5">
            <Tytuł>Chłopaki nie płaczą</Tytuł>
            <DataPremiery>06-12-2000</DataPremiery>
            <Kraj>Polska</Kraj>
            <Reżyser>Olaf Lubaszenko</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="4">
            <Tytuł>Miś</Tytuł>
            <DataPremiery>06-12-1980</DataPremiery>
            <Kraj>Polska</Kraj>
            <Reżyser>Stanisław Bareja</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="5">
            <Tytuł>To właśnie miłość</Tytuł>
            <DataPremiery>06-12-2003</DataPremiery>
            <Kraj>Francja</Kraj>
            <Kraj>USA</Kraj>
            <Kraj>Wielka Brytania</Kraj>
            <Reżyser>Richard Curtis</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="3">
            <Tytuł>Ace Ventura: Psi detektyw</Tytuł>
            <DataPremiery>06-12-1994</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Tom Shadyac</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="3">
            <Tytuł>Głupi i głupszy</Tytuł>
            <DataPremiery>06-12-1994</DataPremiery>
            <Kraj>USA</Kraj>
            <Reżyser>Bobby Farrally</Reżyser>
        </Film>
        <Film IdGatunku="Komedia" Ocena="4">
            <Tytuł>Jak rozpętałem drugą wojnę światową</Tytuł>
            <DataPremiery>06-12-1969</DataPremiery>
            <Kraj>Polska</Kraj>
            <Reżyser>Tadeusz Chmielewski</Reżyser>
        </Film>       
    </Filmy>
    
</BazaFilmów>
